"""Territory Manager Kingdom infrastructure system.

Generated by Mason Infrastructure Forge. This file is staged for Kingdom use but
is blocked by the Manny approval gate until explicitly approved.
"""

from __future__ import annotations

from datetime import datetime, timezone
from pathlib import Path
from typing import Any

SYSTEM_NAME = 'Territory Manager'
SYSTEM_KEY = 'territory_manager'
DATA_FOLDER = Path('C:\\Users\\User\\Desktop\\PUTER\\RAMFAM_KINGDOM_BRAIN\\07_TERRITORIES')
MANNY_APPROVAL_REQUIRED = True
APPROVAL_STATUS = "pending_manny_approval"


def run_territory_manager(request: str, context: dict[str, Any] | None = None) -> dict[str, Any]:
    """Run the staged Territory Manager workflow after request validation."""
    request_text = str(request or "").strip()
    DATA_FOLDER.mkdir(parents=True, exist_ok=True)
    return {
        "system": SYSTEM_NAME,
        "system_key": SYSTEM_KEY,
        "status": APPROVAL_STATUS,
        "request": request_text,
        "context": dict(context or {}),
        "data_folder": str(DATA_FOLDER),
        "approval_required": MANNY_APPROVAL_REQUIRED,
        "approval_gate": {
            "required": True,
            "approver": "Manny",
            "status": APPROVAL_STATUS,
        },
        "summary": f"{SYSTEM_NAME} received the request and is staged pending Manny approval.",
        "created": datetime.now(timezone.utc).isoformat(),
    }


def territory_manager_system(request: str, context: dict[str, Any] | None = None) -> dict[str, Any]:
    """Compatibility wrapper for Atlas/Mason routing."""
    return run_territory_manager(request, context)


__all__ = [
    "SYSTEM_NAME",
    "SYSTEM_KEY",
    "DATA_FOLDER",
    "MANNY_APPROVAL_REQUIRED",
    "APPROVAL_STATUS",
    "run_territory_manager",
    "territory_manager_system",
]


if __name__ == "__main__":
    import json

    print(json.dumps(run_territory_manager("Territory Manager smoke test"), indent=2, ensure_ascii=False))
